### ISSUE TITLE
Visualitation Tracers for point lens

### ISSUE THREAD

**Issue by felavila** [Jammy2211/autolens_workspace#10]
Hi, I am Felipe Avila, a master degree student from Universidad de Valparaíso, Chile. I am trying to use PyAutoLens to model qso Gravitational lensing. I started understanding the example notebooks in the point_source file, but when I try to run the image in the jupyter "visuals.ipynb(/autolens/autolens_workspace/notebooks/point_source/simulators)". I can't observe anything, also I try to use the tracers in the basic example in the from page of the GitHub and in theses cases it works fine. So my question is, these is a just my problem or maybe could be other type of problem.

Thanks for your help and I apologize for my English.
Cheers
Felipe

**Comment by Jammy2211** [comment]
I'm unsure what happened, but there shouldn't be a `visuals.ipynb` file in `autolens_workspace/notebooks/point_source/simulators`, must of been an error on my part! So, ignore that file!

The other 3 notebooks should be there and illustrate how to simulate a point source dataset. A word of warning, these simulations can often simulate multiple points incorrectly, I can expand on this if it is important for what you are trying to do.

Are you ultimately looking to fit a point source dataset of your own? The modeling scripts all work as intended, and simply require you to plug in your own values for the arc second positions.

Finally, point-source specific visualization is a feature currently in progress and not available in the autolens version you are on (e.g. a `PointSourceDictPlotter`, `PointSourceDatasetPlotter`). If these would be useful, I can do a release including them as I implemented them last week (I am still working on other aspects of point source visualization).

**Comment by felavila** [comment]
For the moment, i started whit the visualization part, before to try to do the fitting, but now i just try to fit some of the the qso and compare the results whit my own work whit gravlens from Keeton. Thanks for your clear and fast answer.
