### ISSUE TITLE
Issues with autolens installation

### ISSUE THREAD

**Issue by igixri** [Jammy2211/autolens_workspace#11]
Hello!

I was trying to install autolens onto my laptop so that I could import it to use in my Jupyter notebook, but I kept running into issues when I was trying to pip install it through anaconda. This is the error I got:

ERROR: Could not install packages due to an EnvironmentError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\igixr\\AppData\\Local\\Temp\\pip-install-k6oej0xp\\autofit\\test_autofit/database/mass_sie__source_sersic/phase_mass[sie]_source[bulge]/settings__imaging[grid_sub_2]__lens[pos_off]/dynesty_static[nlive_50__bound_multi_vol_dec_0.5_vol_check_2.0__enlarge_1.0__sample_rwalk_walks_5_facc_0.2]'
Does anyone know how to solve this issue? I went to the directory to try and find the folder, but it looks like the pip-install-k6oej0xp folder doesn't exist (and the number/letter combination changes every time I rerun the code). For reference, my system is Windows 64-bit and my version of Python should be Python 3.

Thank you!

**Comment by Jammy2211** [comment]
Hi,

This is a really weird issue, could you copy and paste the command line instructions you go through to get to this point? Will help me try and replicate these issue.

**Comment by igixri** [comment]
I apologize, I realized belatedly that I had not activated the conda environment before trying to pip install autolens. However, when I did that, I received another error. The final message that the terminal sent was:

"Failed to build Cython matplotlib numpy scikit-image scipy pyquad
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly"

The actual terminal error output is too long to paste here, but it starts with:

 "ERROR: Command errored out with exit status 1:
   command: 'C:\Users\igixr\.conda\envs\autolens\python.exe' 'C:\Users\igixr\AppData\Local\Temp\pip-standalone-pip-_qb17h4_\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\igixr\AppData\Local\Temp\pip-build-env-j8v317mg\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.18' 'numpy==1.14.5; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.3'
       cwd: None"

It would be great if you could help me with this error. Please let me know if you need more information from my end.

**Comment by Jammy2211** [comment]
Good news that we have a new error, the previous one was pretty terrifying!

Could you copy and paste the instructions that you go through to get to that error, I should be able to help from there.

**Comment by igixri** [comment]
Here's what I did: https://pastebin.com/JbL5qaUf
Hopefully, this looks more familiar to you!

**Comment by Jammy2211** [comment]
The issues are specific to installing autolens in Windows, which is still relatively untested and generally more difficult.

I am working on some fixes to try and make it easier, but this will take a day or so. In case you are unaware, you can begin using PyAutoLens via binder, which runs in a web browser. The memory / run times are a bit slow, but it'll help you get familiar with the software:

https://mybinder.org/v2/gh/Jammy2211/autolens_workspace/HEAD

**Comment by igixri** [comment]
I'm sorry for the late response to this comment. I think I will be able to use PyAutoLens through binder for the time being, as I am still getting the same errors when trying to pip install on Windows. Thank you for the help!

**Comment by Jammy2211** [comment]
Apologies for the long time to fix this, but the new version (https://github.com/Jammy2211/PyAutoLens/releases/tag/2021.8.12.1) should install without issue if it is still of use to you.

Albeit, Windows likes to cause unexpected issues, so maybe another problem will crop up!

**Comment by igixri** [comment]
Thank you! This new version does install properly on Windows. I don't seem to be having any issues yet, but I will let you know if they do show up.

Again, thank you so much for your help!
