### ISSUE TITLE
Autolens: Binder 404 error from Chapter 2

### ISSUE THREAD

**Issue by PeterEDz** [Jammy2211/autolens_workspace#13]
On Binder the following the link 

https://hub.gke2.mybinder.org/user/jammy2211-autolens_workspace-w76xgxdm/tree/notebooks/howtolens/chapter_2_lens_modeling/tutorial_6_masking_and_positions.ipynb

gives a 404 "You are requesting a page that does not exist!" when run from "readthedocs" Chapter 2: Lens Modelling: Tutorial 6. Tutorials 5 - 8 all do the same. (I started with 7 because I was looking for something specific.)

Is this a question of the pages not having been written yet, or is it a fault/bug?

FWIW Ubuntu 22.04.1 Pyautolens installed via pip.

Many thanks

**Comment by Jammy2211** [comment]
We are having a bit of a night mare getting a new pip release out, which has lead to issues like this.

The tutorials are visible on the `master` branch of the `autolens_workspace`:

https://github.com/Jammy2211/autolens_workspace/tree/release/scripts/howtolens/chapter_2_lens_modeling

To get the one you want to display in binder, you can use the following link:

https://mybinder.org/v2/gh/Jammy2211/autolens_workspace/release?filepath=notebooks/howtolens/chapter_2_lens_modeling/tutorial_5_masking_and_positions.ipynb

Out of curiosity, is there a reason you are using the Binder?

**Comment by PeterEDz** [comment]
Not really. It launches when I click on the link. The code appears in a notebook on Binder which is executable, so I use it :-)

I tried another link just now ( https://hub.gke2.mybinder.org/user/jammy2211-autolens_workspace-0pf6m89q/notebooks/notebooks/howtolens/chapter_2_lens_modeling/tutorial_3_realism_and_complexity.ipynb ) which is throwing a 424 with the comments:
"We can't seem to find the Binder page you are looking for.
424 error

Here are some helpful tips.

Is this a Binder that you created?

Your Binder stopped due to an error or it was removed due to age or inactivity.

Return to the [Binder home page](https://gke.mybinder.org/) to retry creating your Binder.
Did someone give you this Binder link?

If so, the link is outdated or incorrect. Recheck the link for typos or ask the person who gave you the link for an updated link. A shareable Binder link should look like https://gke.mybinder.org/v2/gh/....
[Binder home page](https://gke.mybinder.org/)"

**Comment by Jammy2211** [comment]
To use the latest notebooks, you can open a binder to the whole `autolens_workspace`  via:

https://mybinder.org/v2/gh/Jammy2211/autolens_workspace/master

Then navigate to `notebooks/howtolens`.

Binder can sometimes be a bit unreliably or cut-out, so the error above could be to do with that.

**Comment by PeterEDz** [comment]
Thanks.

I followed your link to notebooks/howtolens

FYI you have two chapters numbered "4" : "chapter_4_inversions" and "chapter_4_pixelations"

Is there a requirement for system 3.7? I am getting errors from lens_modelling that may indicate a Python 3.7 error
e.g. 

"/srv/conda/envs/notebook/lib/python3.7/site-packages/autoarray/dataset/plot/imaging_plotters.py in subplot_imaging(self)"

Normally I would run 3.10, which I had to upgrade to in order to get autolens to run (installed via pip).

It's a great package and if I can do anything to help let me know. Email me (I believe you have my address) to discuss details

**Comment by Jammy2211** [comment]
Thanks for the info regarding notebooks, duplicaitons and issues.

A lot of this is caused by us having not done a release in a long time, as we are trying to move to an automated build release.

I think I need to just push this through, as it will fix the issues (or bring to light issues that are actually worth fixing). I'll let you know when I do this, but I will try and prioritize it this week.

> It's a great package and if I can do anything to help let me know. Email me (I believe you have my address) to discuss details

I don't think I have your email address?

**Comment by PeterEDz** [comment]
pdzwig@summaventures.com (please delete)
