### ISSUE TITLE
(Chapter 1 / Tutorial 4) Needs Updation

### ISSUE THREAD

**Issue by harshitjindal** [Jammy2211/autolens_workspace#3]
In `howtolens/chapter_1_introduction/tutorial_4_planes.ipynb`, when we trace the source galaxy's light 'back' from the source-plane grid using ```aplt.plane.convergence(plane=source_plane, grid=source_plane_grid)```, it does not produce any output even when the cell runs successfully.

**Comment by harshitjindal** [comment]
update title

**Comment by Jammy2211** [comment]
Finally done!
