### ISSUE TITLE
autofit version problems

### ISSUE THREAD

**Issue by shawnknabel** [Jammy2211/autolens_workspace#5]
Good evening!

I'm really looking forward to working with this software. I'm having an issue with installation.

I followed the pip install instructions. When I first installed, I received this error:
ERROR: autogalaxy 0.10.0 has requirement autofit==0.59.1, but you'll have autofit 0.59.3 which is incompatible.

Everything else seemed to go smoothly. I went ahead and ran the test script and got:

File "/home/shawn/Desktop/autolens_workspace/examples/model/intro/lens_sie__source_sersic.py", line 26, in <module>
    import autofit as af
  File "/home/shawn/miniconda3/lib/python3.7/site-packages/autofit/__init__.py", line 38, in <module>
    from .non_linear.optimize.downhill_simplex import DownhillSimplex
ModuleNotFoundError: No module named 'autofit.non_linear.optimize'

So I thought maybe I just needed to revert to autofit 0.59.1. It told me autolens requires 0.59.3. When I tried to reinstall autolens, it automatically updated to 0.59.3.

It took me in a circle a few times, and I need some help. It's probably something I'm missing or made a mistake during install, so I would appreciate any assistance or advice!

Thank you very much.
Shawn

**Comment by Jammy2211** [comment]
My bad, fixed via email :).
